//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistic.UILayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMessage
    {
        public int MessageID { get; set; }
        public string MessageSender { get; set; }
        public string MessageReciver { get; set; }
        public string MEssageSubject { get; set; }
        public string MessageConcent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string SenderName { get; set; }
        public string ReciverName { get; set; }
    }
}
